const { contextBridge, ipcRenderer, webUtils } = require('electron');
// Electron prefixes rejected invocations with the channel name; show only the actionable message.
const call = (channel, ...args) => ipcRenderer.invoke(channel, ...args).catch(error => {
    throw new Error(String(error?.message || error).replace(/^Error invoking remote method '[^']+': (?:Error: )?/, ''));
});
contextBridge.exposeInMainWorld('deck', {
    platform: process.platform,
    // Automated runs measure the real engine's output; normal launches never expose internals.
    testMode: process.env.PULSEDECK_TEST === '1',
    requestMicrophone: () => call('audio:microphone'),
    getLibrary: () => call('library:get'),
    importSounds: () => call('library:import'),
    dropSounds: files => call('library:drop', Array.from(files, file => webUtils.getPathForFile(file))),
    readSound: id => call('library:read', id),
    editSound: (id, patch) => call('library:edit', id, patch),
    removeSound: id => call('library:remove', id),
    reorderSounds: ids => call('library:reorder', ids),
    saveSettings: patch => call('settings:save', patch),
    saveCapture: (bytes, duration, name) => call('capture:save', bytes, duration, name),
    readCapture: id => call('capture:read', id),
    renameCapture: (id, name) => call('capture:rename', id, name),
    removeCapture: id => call('capture:remove', id),
    importCapture: (name, bytes) => call('capture:import', name, bytes),
    captureToPad: (id, name, playback) => call('capture:toPad', id, name, playback),
    saveRecording: (name, bytes) => call('recording:save', name, bytes),
    ttsInfo: () => call('tts:info'),
    ttsVoices: refresh => call('tts:voices', Boolean(refresh)),
    ttsSynthesize: request => call('tts:synthesize', request),
    ttsCancel: requestId => call('tts:cancel', requestId),
    ttsSave: (resultId, name, volume) => call('tts:save', resultId, name, volume),
    createCollection: (name, clipIds) => call('collection:create', name, clipIds),
    renameCollection: (id, name) => call('collection:rename', id, name),
    deleteCollection: id => call('collection:delete', id),
    addToCollection: (id, clipIds) => call('collection:add', id, clipIds),
    removeFromCollection: (id, clipIds) => call('collection:remove', id, clipIds),
    reorderCollection: (id, clipIds) => call('collection:reorder', id, clipIds),
    createGroup: name => call('group:create', name),
    renameGroup: (id, name) => call('group:rename', id, name),
    deleteGroup: id => call('group:delete', id),
    saveQueue: entries => call('queue:save', entries),
    listProjects: () => call('project:list'),
    createProject: name => call('project:create', name),
    openProject: id => call('project:open', id),
    addProjectAsset: (id, bytes, meta) => call('project:addAsset', id, bytes, meta),
    readProjectAsset: (id, assetId) => call('project:readAsset', id, assetId),
    saveProject: (id, project) => call('project:save', id, project),
    saveProjectDraft: (id, project) => call('project:draft', id, project),
    saveProjectCopy: (id, project, name) => call('project:copy', id, project, name),
    renameProject: (id, name) => call('project:rename', id, name),
    deleteProject: id => call('project:delete', id),
    discardProject: id => call('project:discard', id),
    closeProject: id => call('project:close', id),
    recoverableProjects: () => call('project:recoverable'),
    importStudioFile: () => call('studio:importFile'),
    saveStudioSound: (projectId, revision, name, color, bytes) => call('studio:saveSound', projectId, revision, name, color, bytes),
    exportWav: (name, bytes) => call('export:wav', name, bytes),
    exportOriginal: id => call('clip:exportOriginal', id),
    createBackup: () => call('backup:create'),
    restoreBackup: () => call('backup:restore'),
    openDriver: () => call('guide:driver'),
    openData: () => call('data:open'),
    setAudioActive: active => call('audio:active', Boolean(active)),
    onShortcut: callback => ipcRenderer.on('shortcut', (_event, action) => callback(action)),
    toggleOverlay: show => call('overlay:toggle', show),
    overlayVisible: () => call('overlay:visible'),
    overlayState: state => call('overlay:state', state),
    updateState: () => call('update:state'),
    checkForUpdates: () => call('update:check'),
    installUpdate: () => call('update:install'),
    openReleases: () => call('update:releases'),
    onUpdate: callback => ipcRenderer.on('update', (_event, state) => callback(state)),
    version: () => call('app:version'),
    onOverlayVisible: callback => ipcRenderer.on('overlay-visible', (_event, visible) => callback(visible))
});
