const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('deck', {
    platform: process.platform,
    requestMicrophone: () => ipcRenderer.invoke('audio:microphone'),
    getLibrary: () => ipcRenderer.invoke('library:get'),
    importSounds: () => ipcRenderer.invoke('library:import'),
    dropSounds: files => ipcRenderer.invoke('library:drop', Array.from(files, file => webUtils.getPathForFile(file))),
    readSound: id => ipcRenderer.invoke('library:read', id),
    editSound: (id, patch) => ipcRenderer.invoke('library:edit', id, patch),
    removeSound: id => ipcRenderer.invoke('library:remove', id),
    reorderSounds: ids => ipcRenderer.invoke('library:reorder', ids),
    saveSettings: patch => ipcRenderer.invoke('settings:save', patch),
    saveCapture: (bytes, duration, name) => ipcRenderer.invoke('capture:save', bytes, duration, name),
    readCapture: id => ipcRenderer.invoke('capture:read', id),
    renameCapture: (id, name) => ipcRenderer.invoke('capture:rename', id, name),
    removeCapture: id => ipcRenderer.invoke('capture:remove', id),
    importCapture: (name, bytes) => ipcRenderer.invoke('capture:import', name, bytes),
    openDriver: () => ipcRenderer.invoke('guide:driver'),
    openData: () => ipcRenderer.invoke('data:open'),
    setAudioActive: active => ipcRenderer.invoke('audio:active', Boolean(active)),
    onShortcut: callback => ipcRenderer.on('shortcut', (_event, action) => callback(action)),
    toggleOverlay: show => ipcRenderer.invoke('overlay:toggle', show),
    overlayVisible: () => ipcRenderer.invoke('overlay:visible'),
    overlayState: state => ipcRenderer.invoke('overlay:state', state),
    updateState: () => ipcRenderer.invoke('update:state'),
    checkForUpdates: () => ipcRenderer.invoke('update:check'),
    installUpdate: () => ipcRenderer.invoke('update:install'),
    openReleases: () => ipcRenderer.invoke('update:releases'),
    onUpdate: callback => ipcRenderer.on('update', (_event, state) => callback(state)),
    version: () => ipcRenderer.invoke('app:version'),
    onOverlayVisible: callback => ipcRenderer.on('overlay-visible', (_event, visible) => callback(visible))
});
